In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 

In [3]:
np.__version__

'2.2.6'

In [5]:
import numpy as np
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [6]:
x.dtype

dtype('int64')

In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
y=np.array([[1,2,3],[4,5,6]])

In [10]:
print
(y.ndim)

2

In [11]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
y.sort()

In [14]:
y.shape

(2, 3)

In [15]:
y.size

6

In [16]:
)print(x.size)

4


In [22]:
a=np.array(88)
b=np.array([1,2,3])
c=np.array([[10,20,30],[40,50,60]])
print(a,a.ndim)
print(b,b.ndim)
print(c,c.ndim)

88 0
[1 2 3] 1
[[10 20 30]
 [40 50 60]] 2


1

In [25]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [40]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

(2, 3)
2
int64
6


In [50]:
arr=np.array([10,20,30,40,50])

In [51]:
arr[2]

np.int64(30)

In [52]:
arr

array([10, 20, 30, 40, 50])

In [53]:
arr

array([10, 20, 30, 40, 50])

In [54]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[1,2])

6


In [55]:
arr2[0:,1:]

array([[2, 3],
       [5, 6]])

In [56]:
arr2.ndim

2

In [60]:
arr=np.array([1,2,3])
x=arr.view()
arr[0]=12


In [61]:
x

array([12,  2,  3])

In [62]:
arr

array([12,  2,  3])

In [67]:
arr.reshape(3)

array([12,  2,  3])

In [68]:
x

array([12,  2,  3])

In [69]:
x=np.array([[1,2,3],[4,5,6]])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
x=np.array([[1,2,3,4,5,6,7,8]])
for y in x:
    for a in y:
        print(a)
        print(y)
     

1
[1 2 3 4 5 6 7 8]
2
[1 2 3 4 5 6 7 8]
3
[1 2 3 4 5 6 7 8]
4
[1 2 3 4 5 6 7 8]
5
[1 2 3 4 5 6 7 8]
6
[1 2 3 4 5 6 7 8]
7
[1 2 3 4 5 6 7 8]
8
[1 2 3 4 5 6 7 8]


In [76]:
x=np.array([[[1,2,3,4,5,6,7,8]]])
for y in np.nditer(x):
    print(y)

1
2
3
4
5
6
7
8


In [78]:
a=np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [79]:
print(a,b)

[1 2] [3 4]


In [80]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [81]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [94]:
arr=np.array([1,-2,3,4,5,6])
print(np.array_split(arr,1))
print(np.array_split(arr,2))
print(np.array_split(arr,3))
arr.sort()
print(arr)

[array([ 1, -2,  3,  4,  5,  6])]
[array([ 1, -2,  3]), array([4, 5, 6])]
[array([ 1, -2]), array([3, 4]), array([5, 6])]
[-2  1  3  4  5  6]


In [97]:
arr=np.array([10,20,30,40])
np.where(arr==30)


(array([2]),)

In [98]:
x=np.array([1,2,3,4,5,6,7,8,9,10])

In [104]:
x=np.array([[1,2,3,4,5,6,7,8]])
x

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [105]:
np.random.rand(5)

array([0.02437197, 0.0732382 , 0.86856994, 0.46416329, 0.37980024])

In [107]:
np.random.randint(1,10,5)

array([7, 3, 2, 6, 3], dtype=int32)

In [108]:
arr=np.random.rand(4,4)

In [109]:
arr

array([[0.18421636, 0.87793879, 0.7618518 , 0.55115108],
       [0.64391659, 0.3049946 , 0.74313476, 0.89015776],
       [0.98808549, 0.05240834, 0.33786074, 0.58087467],
       [0.83558719, 0.18781772, 0.61234857, 0.54083619]])

In [110]:
arr*100

array([[18.42163596, 87.79387851, 76.18517987, 55.11510774],
       [64.39165851, 30.49946016, 74.31347603, 89.01577618],
       [98.80854944,  5.24083357, 33.78607441, 58.08746702],
       [83.55871925, 18.7817716 , 61.23485651, 54.08361885]])

In [111]:
arr*100+2

array([[ 20.42163596,  89.79387851,  78.18517987,  57.11510774],
       [ 66.39165851,  32.49946016,  76.31347603,  91.01577618],
       [100.80854944,   7.24083357,  35.78607441,  60.08746702],
       [ 85.55871925,  20.7817716 ,  63.23485651,  56.08361885]])

In [127]:
b=np.array([10,20,30])

array([10, 20, 30])